---
all:
  hosts:
    axess311.axiros.kjoo.net:
  vars:
    period_between_checks: 5

    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/id_rsa

    remote_project_home: /root
    remote_project_path: "{{ remote_project_home }}/reporter"
...
