---
  - name: Project Setup
    hosts: all
    tasks:

      - name : Copy project into host
        copy:
          src: "{{ playbook_dir }}/../reporter"
          dest: "{{ remote_project_home }}"
      
      - name: Install Pip 
        apt:
          name: python3-pip
          state: latest

      - name: Install virtualenv module
        pip: 
          name: virtualenv
          state: latest
      
      - name: Create venv and instal requirements
        pip: 
          virtualenv: "{{ remote_project_path }}/venv"
          requirements: "{{ remote_project_path }}/requirements.txt"

      - name: Allow start.sh to be runable
        file:
          path: "{{ remote_project_path }}/start.sh"
          mode: "0755"

      - name: Allow stop.sh to be runable
        file:
          path: "{{ remote_project_path }}/stop.sh"
          mode: "0755"
...
