---
  - name: setup the project
    hosts: all
    tasks:

      - name : Copy the project into host
        copy:
          src: "{{project_to_copy}}"
          dest: "{{project_home_remote}}"


      # - name: Clone the github Repo
      #   git:
      #     repo: https://github.com/SamuelSilva2310/System-Reporter.git
      #     dest: "{{project_home_remote}}/"
      #     force: yes
      #     clone: yes
      #     update: yes
      
      # Install Pip
      - name: Install Pip 
        apt:
          name: python3-pip
          state: latest

      - name: Install virtualenv module
        pip: 
          name: virtualenv
          state: latest
      
      - name: Create a Virtualenviroment and instal requirements
        pip: 
          virtualenv: "{{project_path_remote}}/venv"
          requirements: "{{project_path_remote}}/requirements.txt"

      - name: Make shell script runable
        shell: "chmod +x {{project_path_remote}}/run.sh {{project_path_remote}}/stop.sh"

...