---
  - name: Stop report collector
    hosts: all
    tasks:

      - name: Stop report collector
        shell: "bash {{ remote_project_path }}/stop.sh"
        args:
          chdir: "{{ remote_project_path  }}"
        register: output
        changed_when: output.stdout | length == 0
      
      - name: Fetch CSV export
        become: true
        fetch:
          src:  "{{ remote_project_path }}/Output/exports/{{ inventory_hostname }}.csv"
          dest: "{{ playbook_dir }}/../exports/{{ ansible_date_time.epoch }}/{{ inventory_hostname }}.csv"
          flat: yes
        when: output.changed
...
