---
  - name: Stop report collector
    hosts: all
    vars:
      export_folder: "{{ansible_date_time.iso8601}}"
    tasks:

      - name: Stop report collector
        shell: "bash {{ remote_project_path }}/stop.sh"
        args:
          chdir: "{{ remote_project_path  }}"
        register: output
        changed_when: output.stdout | length == 0
      
      - name: Fetch CSV export
        become: true
        fetch:
          src:  "{{ remote_project_path }}/Output/exports/{{ inventory_hostname }}.csv"
          dest: "{{ playbook_dir }}/../exports/{{ export_folder }}/{{ inventory_hostname }}.csv"
          flat: yes
        when: output.changed

      - name: Create Excel Report
        delegate_to: 127.0.0.1
        run_once: true
        shell: "bash {{ playbook_dir }}/../../make_report.sh {{export_folder}} {{report_filename}}"
        when: output.changed

...
