---
  - name: Stop program
    hosts: all
    tasks:

      - name: Run Stop bash Script
        shell: "bash {{project_path_remote}}/stop.sh"
        args:
          chdir: "{{project_path_remote}}"
      
      # - name: Kill the process
      #   ignore_errors: yes
      #   shell: pkill -f main.py
      
      - name: Get the csv export File
        fetch:
          src:  "{{project_path_remote}}/Output/exports/{{inventory_hostname}}.csv"
          dest: "{{playbook_dir}}/../exports/{{ ansible_date_time.epoch }}/{{inventory_hostname}}.csv"
          flat: yes
...
